# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hate}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Jones"]
  s.date = %q{2011-07-31}
  s.default_executable = %q{hate}
  s.email = %q{mojobojo@gmail.com}
  s.executables = ["hate"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "bin/hate",
    "example/main.rb",
    "lib/hate.rb",
    "lib/hate/audio.rb",
    "lib/hate/core.rb",
    "lib/hate/game.rb",
    "lib/hate/graphics.rb",
    "lib/hate/graphics/camera.rb",
    "lib/hate/graphics/color.rb",
    "lib/hate/graphics/light.rb",
    "lib/hate/graphics/manager.rb",
    "lib/hate/graphics/shader.rb",
    "lib/hate/graphics/shaders/lights/point.fragment",
    "lib/hate/graphics/shaders/lights/point.vertex",
    "lib/hate/graphics/shapes.rb",
    "lib/hate/graphics/window.rb",
    "lib/hate/input.rb",
    "lib/hate/network.rb",
    "lib/hate/physics.rb",
    "lib/hate/system.rb",
    "lib/util/gl.rb",
    "lib/util/trollop.rb"
  ]
  s.homepage = %q{http://github.com/boj/hate}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{An OpenGL 3d Ruby Engine}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi-opengl>, [">= 0.2.1"])
      s.add_runtime_dependency(%q<ruby-sdl-ffi>, [">= 0.4"])
    else
      s.add_dependency(%q<ffi-opengl>, [">= 0.2.1"])
      s.add_dependency(%q<ruby-sdl-ffi>, [">= 0.4"])
    end
  else
    s.add_dependency(%q<ffi-opengl>, [">= 0.2.1"])
    s.add_dependency(%q<ruby-sdl-ffi>, [">= 0.4"])
  end
end

